In [4]:
import numpy as np
import pandas as pd

In [5]:
score = [90, 99, 85]
dict1 = {'Treetop':90, 'John':99, 'Smite':85}
dict1

{'Treetop': 90, 'John': 99, 'Smite': 85}

In [6]:
pd.Series(dict1)

Treetop    90
John       99
Smite      85
dtype: int64

In [7]:
Score = [90, 99, 85]
Name = ['Treepop', 'John', 'Smith']

series = pd.Series(data=Score, index=Name)
print(series)

Treepop    90
John       99
Smith      85
dtype: int64


In [8]:
Score2 = np.array(Score)
Name2 = np.array(Name)

print(Score2)
print(type(Score2))

[90 99 85]
<class 'numpy.ndarray'>


In [9]:
series2 = pd.Series(Score2, Name2)
print(series2)

Treepop    90
John       99
Smith      85
dtype: int32


In [10]:
#Pandas Series สามารถเก็บข้อมูลต่างชนิดกันได้ ขณะที่ Numpy Array ไม่ได้
Score = [90, 99, 'Not']
Name = ['Treepop', 'John', 'Smith']

series = pd.Series(Score, Name)
print(series)

Treepop     90
John        99
Smith      Not
dtype: object


In [11]:
#Pandas Series สามารถเก็บข้อมูลโดยตรงได้เลย
series1 = pd.Series(data=['A', 'B', 'C'], index=[1, 2, 3])
print(series1)

1    A
2    B
3    C
dtype: object


In [12]:
#ถ้าไม่ระบุ index Series จะรัน index จาก 0 ให้โดยอัติโนมัติ (auto increment)
series1 = pd.Series(data=['A', 'B', 'C'])
print(series1)

0    A
1    B
2    C
dtype: object


In [13]:
#เข้าถึงสมาชิกสามารถเข้าถึงสมาชิกภายใน Series โดยการเลือกชื่อ index เหมือนเลือก key ของ dict หรือเลือกตำแหน่งของ value ก็ได้เช่นกัน
series1 = pd.Series(data=['Treetop', 'John', 'Kim'], index=['A', 'B', 'C'])
print(series1['A'])
print(series1['B'])
print(series1[0])
print(series1[1])

Treetop
John
Treetop
John


In [14]:
#เข้าถึงสมาชิก 2 สามารถเข้าถึงสมาชิกภายใน Series แบบ Slicing ได้
series1 = pd.Series(data=['Treetop', 'John', 'Kim'], index=['A', 'B', 'C'])
print(series1[1:3])

B    John
C     Kim
dtype: object


In [15]:
#เข้าถึงสมาชิก 3 สามารถเข้าถึงสมาชิกแบบเป็นกลุ่มได้ โดยการส่งindex ที่ต้องการในรูปแบบลิส ให้เป็น argument
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series)

series[[0,2,4]]

series[['John', 'Smith']]

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


John     99
Smith    85
dtype: int64

In [16]:
#เข้าถึงสมาชิก 4 สามารถเข้าถึงสมาชิกแบบเป็นกลุ่มได้ โดยการส่งindex ที่ต้องการในรูปแบบลิส แบบ Boolean ให้เป็น argument
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)

series[[True, False, False, True, True, True]]

Treepop    90
Jim        77
Kim        55
Alex       69
dtype: int64

In [17]:
#เข้าถึงสมาชิก 5 สามารถเข้าถึงสมาชิกแบบเป็นกลุ่มได้ โดยการส่งindex ที่ต้องการในรูปแบบลิส แบบ Boolean ให้เป็น argument โดยที่ Boolean ได้มาจาก Conditional Selection (การเลือกแบบมีเงื่อนไข)
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series)

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


In [18]:
Even_number = np.arange(6)
print(Even_number)
print(Even_number%2==0)
series[Even_number%2==0]

[0 1 2 3 4 5]
[ True False  True False  True False]


Treepop    90
Smith      85
Kim        55
dtype: int64

In [19]:
#การวิเคราะห์ข้อมูลสามารถใช้คำสั่งเดียวกับ numpy วิเคราะห์ข้อมูลภายในได้ เพราะ Pandas สร้างบนพื้นฐาน numpy เช่น คำสั่ง sum mean max std
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series.mean())
print(series.max())
print(series.argmax())
print(series.sum())
print(series.std())

79.16666666666667
99
1
475
15.727894540168647


In [20]:
#การแก้ไขสมาชิกสามารถแก้ไขสมาชิกภายใน Series ได้ โดยการประกาศค่าใหม่เหมือน List
series1 = pd.Series(data=['A', 'B', 'C'], index=[1,2,3])
print(series1)

1    A
2    B
3    C
dtype: object


In [21]:
series1[1] = 'X'
print(series1)

1    X
2    B
3    C
dtype: object


In [22]:
#การเพิ่มสมาชิกสามารถเพิ่มสมาชิกภายใน Series ได้ เหมือนกับการแก้ไข ถ้า index ไม่ซ้ำจะเป็นการเพิ่มสมาชิกแทน
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series)

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


In [23]:
series['Chen'] = 33
print(series)

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
Chen       33
dtype: int64


In [24]:
#การลบสมาชิกสามารถลบสมาชิกภายใน Series ได้ โดยใช้คำสั่ง del
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series)

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


In [25]:
del series['John']
print(series)

Treepop    90
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


In [26]:
#การนำ Series มาบวกกัน Series จะนำเอา Value ที่ Index ตรงกันมารวมกัน เช่น การรวมคะแนนสอบของนักเรียน
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)
print(series)

Treepop    90
John       99
Smith      85
Jim        77
Kim        55
Alex       69
dtype: int64


In [27]:
Score = [10, 33, 44, 77, 22, 11]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series2 = pd.Series(Score, Name)
print(series2)

Treepop    10
John       33
Smith      44
Jim        77
Kim        22
Alex       11
dtype: int64


In [28]:
series + series2

Treepop    100
John       132
Smith      129
Jim        154
Kim         77
Alex        80
dtype: int64

In [29]:
#ถ้าข้อมูลไม่ตรงกันจะขึ้น NaN (NaN = ไม่มีค่า)
Score = [90, 99, 85, 77, 55, 69]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Alex']

series = pd.Series(Score, Name)

Score = [10, 33, 44, 77, 22, 11]
Name = ['Treepop', 'John', 'Smith', 'Jim', 'Kim', 'Viktor']

series2 = pd.Series(Score, Name)

series + series2

Alex         NaN
Jim        154.0
John       132.0
Kim         77.0
Smith      129.0
Treepop    100.0
Viktor       NaN
dtype: float64

In [30]:
#การสร้าง DataFrame
#ต้องระบุ values เป็นแบบ matrix
#ระบุชื่อ row ให้พอดีกับจำนวน row
#ระบุชื่อ column ให้พอดีกับจำนวน column
#ใช้คำสั่ง pd.DataFrame(Values, rows, columns)

import numpy as np
import pandas as pd

values = np.random.randint(0,20,(3,3))
rows = ['A', 'B', 'C']
cols = ['X', 'Y', 'Z']
print(values)

[[ 9 17  7]
 [18 17  0]
 [ 0 10  2]]


In [31]:
#หน้าตาของ df (DataFrame)จะเป็นแบบนี้ 
df = pd.DataFrame(values, rows, cols)
df

X   Y  Z
A   9  17  7
B  18  17  0
C   0  10  2

In [32]:
#เช็ค shape ของ DataFrame
df.shape

(3, 3)

In [33]:
#การเข้าถึงสมาชิกสามารถเข้าถึงสมาชิกภายในDataFrame ได้โดยการเลือกชื่อ column
df['X']

A     9
B    18
C     0
Name: X, dtype: int32

In [34]:
#ไม่แนะนำวิธีนี้
df.X

A     9
B    18
C     0
Name: X, dtype: int32

In [35]:
#การเข้าถึงสมาชิก 2 สามารถเข้าถึงสมาชิกภายในDataFrame ได้โดยการเลือกชื่อหลายๆ columns
df2 = df[['X','Z']]
df2

X  Z
A   9  7
B  18  0
C   0  2

In [36]:
type(df2)

pandas.core.frame.DataFrame

In [37]:
df3 = df['Y']
print(df3)
print(type(df3))

A    17
B    17
C    10
Name: Y, dtype: int32
<class 'pandas.core.series.Series'>


In [38]:
#การเพิ่ม column สามารถเพิ่ม column โดยต้องใส่ให้ครบสมาชิกตามจำนวน rows
df

X   Y  Z
A   9  17  7
B  18  17  0
C   0  10  2

In [39]:
df['P'] = [1,2,3]
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [40]:
#การลบ column, row สามารถลบ column โดยจะต้องระบุแกนที่จะลบ 
#โดย axis = 0 (ค่าเริ่มต้น) คือแกน y หรือ ลบ row axis = 1 คือแกน x หรือ ลบ column
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [41]:
df.drop('Z', axis=1)

X   Y  P
A   9  17  1
B  18  17  2
C   0  10  3

In [42]:
df.drop('A')

X   Y  Z  P
B  18  17  0  2
C   0  10  2  3

In [43]:
#การลบ column, row 2
#เมื่อลบ จะเป็นแค่การแสดงผล ไม่มีผลกับ DataFrame ของจริง
#ถ้าต้องการให้มีผลกับของจริงจะต้องระบุ inplace = True
df2

X  Z
A   9  7
B  18  0
C   0  2

In [44]:
df2.drop('Z', axis=1, inplace=True)
df

F:\Anaconda\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [45]:
#การเข้าถึงสมาชิก 3
#สามารถเข้าถึงสมาชิกภายในDataFrame ได้โดยการเลือกชื่อ row
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [46]:
#ใส่ชื่อ row
df.loc['A']

X     9
Y    17
Z     7
P     1
Name: A, dtype: int64

In [47]:
#ใส่ index ของ row
df.iloc[1]

X    18
Y    17
Z     0
P     2
Name: B, dtype: int64

In [48]:
#การเข้าถึงสมาชิก 4 สามารถเข้าถึงสมาชิกภายในDataFrame ได้โดยการเลือกชื่อหลายๆ row
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [49]:
df.loc[['A','B']]

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2

In [50]:
#การเข้าถึงสมาชิก 5 สามารถเข้าถึงสมาชิกภายในDataFrame ได้โดยการเลือกชื่อทั้ง row และ column เพื่อเลือกสมาชิกที่ต้องการ
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [51]:
df.loc['B','Z']

0

In [52]:
df.loc[['B','C'],['X','Z']]

X  Z
B  18  0
C   0  2

In [53]:
df.loc[['B','C'],['Y']]

Y
B  17
C  10

In [54]:
#การเลือกแบบมีเงื่อนไข
#เหมือนกับการเลือกแบบมีเงื่อนไขของ Series 
#มีประโยชน์อย่างมากในการเลือกเฉพาะข้อมูลที่เราต้องการ คล้ายกับการทำ If-Else
df > 10

X      Y      Z      P
A  False   True  False  False
B   True   True  False  False
C  False  False  False  False

In [55]:
#สมาชิกตัวใดที่เป็นเท็จจะถูกแทนด้วย NaN
df[df > 10]

X     Y   Z   P
A   NaN  17.0 NaN NaN
B  18.0  17.0 NaN NaN
C   NaN   NaN NaN NaN

In [56]:
#การเลือกแบบมีเงื่อนไข 2
#ในทางปฎิบัติเราจะเลือกเป็น column และลบ row ของ column ที่ไม่ผ่านเงื่อนไข
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [57]:
df['X'] > 60

A    False
B    False
C    False
Name: X, dtype: bool

In [58]:
df[df['X'] > 10]

X   Y  Z  P
B  18  17  0  2

In [59]:
#การเลือกแบบมีเงื่อนไข 3
#เราสามารถเลือกเฉพาะ column หลังจากเลือกแบบมีเงื่อนไขแล้ว
df[df['X'] > 10]

X   Y  Z  P
B  18  17  0  2

In [60]:
df[df['X'] > 10]['X']

B    18
Name: X, dtype: int32

In [61]:
df[df['X'] > 10]

X   Y  Z  P
B  18  17  0  2

In [62]:
df[df['X'] > 10][['X','Z']]

X  Z
B  18  0

In [63]:
new_df = df[df['X'] > 10]
new_df

X   Y  Z  P
B  18  17  0  2

In [64]:
new_df[['X','Z']]

X  Z
B  18  0

In [65]:
#การเลือกแบบมีเงื่อนไข 4
#เมื่อเงื่อนไขที่ต้องการมีมากกว่า 1
#เช่นใน DataFrame นี้ เราต้องการ column X เฉพาะที่สมาชิกมีค่าน้อยกว่า 70 กับ column Y ที่สมาชิกมากกว่า 50 
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [66]:
#ก่อนอื่นเราต้องพิจารณาทีละเงื่อนไข

In [67]:
df['X']<70

A    True
B    True
C    True
Name: X, dtype: bool

In [69]:
df['X']>50

A    False
B    False
C    False
Name: X, dtype: bool

In [71]:
df[df['X']<70]

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [70]:
df[df['X']>50]

Empty DataFrame
Columns: [X, Y, Z, P]
Index: []

In [72]:
#ใช้ & แทน and เพื่อเชื่อมเงื่อนไข เนื่องจากค่าความจริงมีมากกว่า 1
#ป.ล. & เป็น bitwise operator
#and เป็น logical operator
df

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [73]:
df[(df['X']<70) & (df['Y']>50)]

Empty DataFrame
Columns: [X, Y, Z, P]
Index: []

In [74]:
#ใช้ | แทน or เพื่อเชื่อมเงื่อนไข เนื่องจากค่าความจริงมีมากกว่า 1
#ป.ล. | เป็น bitwise operator
#or เป็น logical operator
df[(df['X']<70) | (df['Y']>50)]

X   Y  Z  P
A   9  17  7  1
B  18  17  0  2
C   0  10  2  3

In [77]:
#การสร้าง row ที่มากกว่า 1 
#(Multiple-index DataFrame)
#เมื่อต้องการจำแนกประเภทของ rows ให้อยู่เป็นหมวดหมู่โดยที่ไม่กระทบต่อ column 
level1 = ['Japan Car', 'Japan Car', 'Japan Car', 'Europe Car', 'Europe Car', 'Europe Car']
level2 = ['Honda', 'Toyota', 'Mazda', 'Benz', 'BMW', 'Porse']
column = ['ยอดขายปี 2018 (พันล้านบาท)', 'ยอดขายปี 2018 (พันล้านบาท)']
index = list(zip(level1, level2))
revenue = np.random.randint(5, 50, (6,2))
multi_index = pd.MultiIndex.from_tuples(index)
df = pd.DataFrame(revenue, index=multi_index, columns=column)
df

ยอดขายปี 2018 (พันล้านบาท)  ยอดขายปี 2018 (พันล้านบาท)
Japan Car  Honda                           20                           9
           Toyota                           9                          37
           Mazda                           34                          43
Europe Car Benz                            29                          41
           BMW                             20                          22
           Porse                           44                          46